@startuml
Start;
:temp consigna estiu = 20-29ºC;
:temp consigna hivern = 17-26ªC;
:encendre pantalla LCD;
:encendre LEDs;
:encendre detector d'obstacles;
:Llegir detector d'obstacles;
:Llegir temperatura;
:Llegir humitat;
:Llegir brillor illuminació;
:mostrar temp consigna, temp actual, hum i brillor a la pantalla;
repeat
if (35<hum>60 ?) then (SÍ)
 :LED 2 = verd;
 else (NO)
 :LED 2 = vermell;
endif
if (temp = consigna ?) then (SÍ)
 :LED 1 = verd;
 else (NO)
 :LED 1 = vermell;
if (temp > consigna) then (SÍ)
  :LED 3 = blau;
  :encendre ventilació;
  else (NO)
   if (temp < consigna ?) then (SÍ)
   :LED 3 = vermell;
   :encendre calefació;
endif
endif
endif
if (obstacle detectat?) then (SÍ)
 :LED 4 i LED 5 = vermell intermitent;
 :mostrar a la pantalla: ALARMA ACTIVADA: ALERTA;
 if (polsador 1 premut?) then (SÍ)
  :LED 4 i LED 5 = OFF;
  else (NO)
 endif
 else (NO)
 :LED 4 i LED 5 = OFF;
endif
if (polsador 2 premut?) then (SÍ)
 :LED 6, LED 7 i LED 8 = blanc;
  if (X Joystick mogut?) then (A la dreta)
  :augmentar brillor;
  else (A l'esquerra)
  :disminuir brillor;
  endif
 else (NO)
 :LED 6, LED 7 i LED 8 = OFF;
endif
if (Y Joystick mogut?) then (A dalt)
 :augmentar temp cosigna;
else (Abaix)
 :disminuir temp cosigna;
endif
if (Botó Joystick premut?) then (SÍ)
 :temp consigna = 24;
else (NO)
endif
if (polasador 1 premut?) then (SÍ)
 :canviar estació;
else (NO)
endif

@enduml
